### PR TITLE
Add support for turning on tcp keep alive.

### PR DESCRIPTION
**Pull request by youngm**
Attn: @ingenthr

Bringing back to life PR https://github.com/couchbase/spymemcached/pull/8

The original PR looked good except for the one incorrect negation.  So, I fixed that and brought the PR up to master.  All tests pass.

Thanks.

### CODE REVIEW

**Comment by youngm** [comment]
Oops :)  I think it is fixed now.  Thanks @ingenthr

**Comment by youngm** [comment]
One last small change I removed some pom.xml config I had accidentally committed.  I think this is good to go now.  Let me know if I can do anything else to help this along.

**Comment by ingenthr** [comment]
Will have a look here later this afternoon, thanks @youngm !

**Comment by ingenthr** [comment]
merged.  thanks for the fixup and contribution!  will probably skate through the rest of these PRs and cut a release soon.

**Pull request closed without merging**
